name: monolayer

on:
  push:
    paths:
      - 'packages/monolayer/**'

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./packages/monolayer
      - name: Run check:lint
        run: npm run check:lint
        working-directory: ./packages/monolayer

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./packages/monolayer
      - name: Run check:prettier
        run: npm run check:prettier
        working-directory: ./packages/monolayer

  types:
    name: ts@${{ matrix.typescript_version }} zod@${{ matrix.zod_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zod_version: ["3.22.2", "3.22.3", "3.22.4"]
        typescript_version: ["5.4.2", "5.3.3", "5.2.2", "5.1.6"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./packages/monolayer
      - name: Install zod
        run: npm install --save-exact zod@${{ matrix.zod_version }}
        working-directory: ./packages/monolayer
      - name: Run check:type
        run: npm run check:type
        working-directory: ./packages/monolayer
        env:
          TYPESCRIPT_VERSION: ${{ matrix.typescript_version }}

  graph:
    name: Module Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./packages/monolayer
      - name: Run check:skott
        run: npm run check:skott
        working-directory: ./packages/monolayer

  test:
    needs: [lint, format, types, graph]
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install pg_dump
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
          sudo apt-get update
          sudo apt-get -y install postgresql-client-16

      - name: Install dependencies
        run: npm ci
        working-directory: ./packages/monolayer
      - name: Run tests
        run: npm run test
        working-directory: ./packages/monolayer
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

  test-matrix:
    needs: [lint, format, types, graph]
    name: Test kysely@${{ matrix.kysely_version }} zod@${{ matrix.zod_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zod_version: ["3.22.2", "3.22.3", "3.22.4"]
        kysely_version: ["0.27.3", "0.27.2", "0.27.1", "0.27.0"]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install pg_dump
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
          sudo apt-get update
          sudo apt-get -y install postgresql-client-16

      - name: Install dependencies
        run: npm ci
        working-directory: ./packages/monolayer
      - name: Install zod
        run: npm install --save-exact zod@${{ matrix.zod_version }}
        working-directory: ./packages/monolayer
      - name: Run Tests
        run: npm run test
        working-directory: ./packages/monolayer
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          KYSELY_VERSION: ${{ matrix.kysely_version }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, format, types, graph, test, test-matrix]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./packages/monolayer
      - name: Run build
        run: npm run build
        working-directory: ./packages/monolayer
