name: monolayer

on:
  push:
    paths:
      - ".github/workflows/monolayer.yml"
      - "apps/monolayer/**"
      - "internal/**"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install
      - name: Run check
        run: npx turbo check

  test-pg:
    needs: [check]
    name: Test pg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run pg tests
        run: npm run test -w internal/pg
