name: Yount

on:
  push:
    paths:
      - 'packages/yount/**'

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./packages/yount
      - name: Run check:lint
        run: npm run check:lint
        working-directory: ./packages/yount

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./packages/yount
      - name: Run check:prettier
        run: npm run check:prettier
        working-directory: ./packages/yount

  types:
    name: ts@${{ matrix.typescript_version }} zod@${{ matrix.zod_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zod_version: ["3.22.2", "3.22.3", "3.22.4"]
        typescript_version: ["5.4.2", "5.3.3", "5.2.2", "5.1.6"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./packages/yount
      - name: Install zod
        run: npm install --save-exact zod@${{ matrix.zod_version }}
        working-directory: ./packages/yount
      - name: Run check:type
        run: npm run check:type
        working-directory: ./packages/yount
        env:
          TYPESCRIPT_VERSION: ${{ matrix.typescript_version }}

  graph:
    name: Module Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./packages/yount
      - name: Run check:skott
        run: npm run check:skott
        working-directory: ./packages/yount

  test:
    needs: [lint, format, types, graph]
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./packages/yount
      - name: Run test:unit
        run: npm run test:unit
        working-directory: ./packages/yount
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

  test-matrix:
    needs: [lint, format, types, graph]
    name: Test kysely@${{ matrix.kysely_version }} zod@${{ matrix.zod_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zod_version: ["3.22.2", "3.22.3", "3.22.4"]
        kysely_version: ["0.27.3", "0.27.2", "0.27.1", "0.27.0"]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./packages/yount
      - name: Install zod
        run: npm install --save-exact zod@${{ matrix.zod_version }}
        working-directory: ./packages/yount
      - name: Run test:unit
        run: npm run test:unit
        working-directory: ./packages/yount
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          KYSELY_VERSION: ${{ matrix.kysely_version }}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, format, types, graph, test, test-matrix]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./packages/yount
      - name: Run build
        run: npm run build
        working-directory: ./packages/yount
